Add Api for work and setup admin site
storiesofgaatha/gaatha-server pull request #1
Opened 2023-01-10 04:38 UTC by Rup-Narayan-Rajbanshi

- Set up djagno project
- Set up poetry
- Dockerize the app
- Set up postgres
- Set up strawberry
- Added models for work and work image
- Set up admin to add work
- Add Tinymce
- Configure media and static files
- Add filter for works get api
- Added flake8 check in github

2023-01-11 02:09 UTC, AdityaKhatri requested changes

2023-01-11 02:09 UTC, AdityaKhatri commented on apps/work/models.py
> +# Create your models here.
remove this comment

2023-01-11 02:09 UTC, AdityaKhatri commented on apps/work/models.py
> +        RESEARCH = 'research', _('Research')
Is this confirmed with @subinasr and Gaatha team?

2023-01-11 02:09 UTC, AdityaKhatri commented on apps/work/models.py
> +        EXIBITION = 'exibition', _('Exibition')
These are created in the backend and not hard-coded, based on my previous conversation with @subinasr. Please clarify before proceeding.

2023-01-11 02:09 UTC, AdityaKhatri commented on apps/work/models.py
> +class People(models.Model):
This should be in a separate app, and not within work in my opinion.

2023-01-11 02:09 UTC, AdityaKhatri commented on apps/work/models.py
> +    linked_in_url = models.CharField(
```suggestion
    linkedin_url = models.CharField(
```

2023-01-11 02:09 UTC, AdityaKhatri commented on gaatha/urls.py
> +    path('tinymce/', include('tinymce.urls')),
Why is this required? Just curious.

2023-01-11 04:00 UTC, Rup-Narayan-Rajbanshi commented on apps/work/models.py
> +        RESEARCH = 'research', _('Research')
@AdityaKhatri , It is not confirmed but , can be change later when it is confirmed. Till then we can use it for testing.

2023-01-11 04:03 UTC, Rup-Narayan-Rajbanshi commented on apps/work/models.py
> +        EXIBITION = 'exibition', _('Exibition')
@AdityaKhatri  As discussed with @subinasr , it was discussed that these choices would be static.

2023-01-11 04:40 UTC, k9845 commented on apps/work/dataloaders.py
> +from asgiref.sync import sync_to_async
Maintain order of import.

2023-01-11 04:40 UTC, k9845 commented on apps/work/dataloaders.py
> +    return [_map[key] for key in keys]
Seems we can make a common method.

2023-01-11 04:40 UTC, k9845 commented on gaatha/schema.py
> +    people: List[PeopleType] = strawberry.django.field()
Shouldn't here be `PeopleListType`.

2023-01-11 04:45 UTC, thenav56 requested changes
Let's remove `apps/work/views.py` and maybe start with a basic test case and run the test in CI as well.

2023-01-11 04:45 UTC, thenav56 commented on apps/work/filters.py
> +    tag: List[TagEnum] | None
Newer python has direct support for typing for basic types. No need to import List from typing.
```suggestion
    category: list[CategoryEnum] | None
    tag: list[TagEnum] | None
```

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +
```suggestion
```

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +    class Category(models.TextChoices):
Just a NOTE: Since we are using GraphQL and it has good support for ENUM we can also just use SmallInteger as well. It will give a good boost to the query.

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +    duration = models.CharField(max_length=100, blank=True)
Why is it CharField?

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +    art_work = models.FileField(null=True, blank=True, upload_to="art_works")
```suggestion
    art_work = models.FileField(null=True, blank=True, upload_to="work/art-works")
```

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +        upload_to="cover_images",
```suggestion
        upload_to="work/cover-images",
```

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +    area = models.CharField(max_length=50, blank=True)
Not an integer/decimal/float?

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +    status = models.CharField(max_length=250, verbose_name=_('Status'))
Can't we define an enum here as well?

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +        blank=True,
Why?

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +        blank=True,
Why

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +        upload_to="workimage_image",
```suggestion
        upload_to="work-image/images/",
```

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +        upload_to="profile_pictures",
```suggestion
        upload_to="people/profile-pictures",
```

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +        upload_to="art_works",
```suggestion
        upload_to="people/art-works",
```

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +    )
Can we make this Enum as well? @AdityaKhatri @subinasr

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +    linked_in_url = models.CharField(
https://docs.djangoproject.com/en/4.1/ref/models/fields/#urlfield
```suggestion
    linked_in_url = models.URLField(
```

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +    instagram_url = models.CharField(
```suggestion
    instagram_url = models.URLField(
```

2023-01-11 04:45 UTC, thenav56 commented on apps/work/models.py
> +        return str(self.name)
```suggestion
        return self.name
```

2023-01-11 04:45 UTC, thenav56 commented on apps/work/types.py
> +    async def image(self, info: Info) -> Optional[FileFieldType]:
For new version of python, this should work
```suggestion
    async def image(self, info: Info) -> FileFieldType | None:
```

2023-01-11 04:45 UTC, thenav56 commented on docker-compose.yml
> +services:
Let's define a docker-compose file version.
https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix
```yaml
version: '3.8'

```

2023-01-11 04:45 UTC, thenav56 commented on docker-compose.yml
> +      SECRET_KEY: ${SECRET_KEY:-django-insecure-xxxxxxxx-do-not-use-in-production}
```suggestion
      SECRET_KEY: ${DJANGO_SECRET_KEY:-?}
```

2023-01-11 04:45 UTC, thenav56 commented on docker-compose.yml
> +      DB_PORT: 5432
```suggestion
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
```

2023-01-11 04:45 UTC, thenav56 commented on docker-compose.yml
> +      - .env
Let's try not to use .env for containers.
```suggestion
```

2023-01-11 04:45 UTC, thenav56 commented on gaatha/urls.py
> +    path('tinymce/', include('tinymce.urls')),
https://django-tinymce.readthedocs.io/en/latest/installation.html#id2

2023-01-11 04:45 UTC, thenav56 commented on gaatha/urls.py
> +urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
This also goes in `if settings.DEBUG`

2023-01-11 04:45 UTC, thenav56 commented on pyproject.toml
> +authors = ["rup <rup.rajbanshi@togglecorp.com>"]
```suggestion
authors = ["TC-DEV <dev@togglecorp.com>"]
```

2023-01-11 04:45 UTC, thenav56 commented on scripts/run_develop.sh
> +python manage.py collectstatic --noinput &
This shouldn't be required for the development.

2023-01-11 04:45 UTC, thenav56 commented on utils.py
> +        file = file[0]
Is there a reason behind this? This should be done before calling build_url

2023-01-11 04:45 UTC, thenav56 commented on utils.py
> +def build_url(file, request):
Also, let's add typing here as well.

2023-01-11 04:45 UTC, thenav56 commented on gaatha/settings.py
> +    DEBUG=(bool, True),
Default should be always False
```suggestion
    DEBUG=(bool, False),
```

2023-01-11 04:45 UTC, thenav56 commented on gaatha/settings.py
> +    SECRET_KEY=(str, 'django-insecure-pm5c((7v2kh7btd(o%2exi4+6_ui1pso-6naxq-6zuaxs7sq+%'),
Let's never add a secret key here
```suggestion
    DJANGO_SECRET_KEY=str,
```

2023-01-11 04:45 UTC, thenav56 commented on gaatha/settings.py
> +    DB_PORT=(str, 5432),
Let's not define default values here. Use docker-compose as a stack to define there. From an application point-of-view, the application doesn't have any knowledge of the stack it is running on.
Also, DB_PORT is `int` not `str`.
```suggestion
    DB_NAME=str,
    DB_USER=str,
    DB_PWD=str,
    DB_HOST=str,
    DB_PORT=int,
```

2023-01-11 04:45 UTC, thenav56 commented on gaatha/settings.py
> +TIME_ZONE = 'UTC'
Use env for this as well. Use Kathmandu timzeone as default in docker-compose.yml

2023-01-11 04:45 UTC, thenav56 commented on gaatha/settings.py
> +    MEDIA_URL = "/media/"
This will be the default, we can mutate this later according to other services used.
```suggestion
# Default: Settings for local storage and local staticfiles
STATIC_URL = "/staticfiles/"
MEDIA_URL = "/media/"
```

2023-01-11 04:45 UTC, thenav56 commented on gaatha/schema.py
> +        return options
We can't use await with the return?
```suggestion
        return await get_work_filter_options()
```

2023-01-11 04:45 UTC, thenav56 commented on apps/work/types.py
> +        return build_url(result, info.context['request'])
Why do we need dataloader here? Can't use `self.art_work`?

2023-01-11 04:45 UTC, thenav56 commented on apps/work/types.py
> +        result = await info.context["work_cover_image_loader"].load(self.id)
Why do we need dataloader here? Can't use `self.cover_image`?

2023-01-11 04:45 UTC, thenav56 commented on apps/work/types.py
> +        result = await info.context["people_profile_picture_loader"].load(self.id)
Why do we need dataloader here? Can't use `self.profile_picture`?

2023-01-11 04:47 UTC, thenav56 commented on gaatha/schema.py
> +    people: List[PeopleType] = strawberry.django.field()
We will need to use pagination here.

2023-01-11 05:03 UTC, Rup-Narayan-Rajbanshi commented on apps/work/models.py
> +    duration = models.CharField(max_length=100, blank=True)
@thenav56 it can be in years, or  month, or days etc to it is decided to keep charfield.

2023-01-11 10:28 UTC, Rup-Narayan-Rajbanshi commented on apps/work/models.py
> +    area = models.CharField(max_length=50, blank=True)
@thenav56 , due to variation of units for area, we have decided to keep it char field.

2023-01-11 10:28 UTC, Rup-Narayan-Rajbanshi commented on apps/work/models.py
> +    area = models.CharField(max_length=50, blank=True)
@thenav56 , due to variation of units for area, we have decided to keep it char field.

2023-01-11 10:33 UTC, Rup-Narayan-Rajbanshi commented on apps/work/models.py
> +    status = models.CharField(max_length=250, verbose_name=_('Status'))
@thenav56 it is the requirement to keep free text.

2023-01-11 14:47 UTC, thenav56 commented on apps/work/models.py
> +    duration = models.CharField(max_length=100, blank=True)
Okay

2023-01-11 14:47 UTC, thenav56 commented on apps/work/models.py
> +    area = models.CharField(max_length=50, blank=True)
Okay.

2023-01-11 14:48 UTC, thenav56 commented on apps/work/models.py
> +    status = models.CharField(max_length=250, verbose_name=_('Status'))
Can you share where these requirements are defined?

2023-01-12 04:22 UTC, Rup-Narayan-Rajbanshi commented on apps/work/models.py
> +    status = models.CharField(max_length=250, verbose_name=_('Status'))
@thenav56 , for now my requirement are defined by @subinasr

2023-01-12 05:58 UTC, AdityaKhatri commented on apps/work/models.py
> +    )
I think it can be a free text thing, they'll be adding new people with different kinds of positions and qualifications.

2023-01-12 09:51 UTC, subinasr commented on apps/work/models.py
> +        RESEARCH = 'research', _('Research')
Yes, we've decided to make this dynamic now.

2023-01-12 10:41 UTC, subinasr commented on apps/work/models.py
> +        EXIBITION = 'exibition', _('Exibition')
Yes, these are gonna be dynamic too.

2023-01-12 10:42 UTC, subinasr commented on apps/work/models.py
> +class People(models.Model):
Agreed.  This should be a separate entity and not within work.

2023-01-12 10:45 UTC, subinasr commented on apps/work/models.py
> +    status = models.CharField(max_length=250, verbose_name=_('Status'))
Yes @thenav56 , it has been decided to keep it a free text as for now.

2023-01-12 10:48 UTC, subinasr commented on apps/work/models.py
> +    )
I discussed this with the Gaatha team. They want flexibility and requested both these fields to be free text.
But if you think this should be Enum, let's discuss it. We can ask them to consider this.

2023-01-14 06:21 UTC, thenav56 commented on docker-compose.yml
> +      SECRET_KEY: ${SECRET_KEY:-django-insecure-xxxxxxxx-do-not-use-in-production}
My bad, we need this
```bash
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?err}
```

2023-01-16 08:48 UTC, thenav56 approved these changes

2023-01-16 08:55 UTC, k9845 approved these changes

2023-01-16 08:55 UTC, k9845 commented on apps/people/models.py
> +        upload_to="profile_pictures",
```suggestion
        upload_to="people/profile_pictures",
```

2023-01-16 08:55 UTC, k9845 commented on apps/people/models.py
> +        upload_to="art_works",
```suggestion
        upload_to="people/art_works",
```

2023-01-25 07:01 UTC, bimal125 approved these changes

2023-01-30 04:52 UTC, merged