Feature/remove project add work type
storiesofgaatha/gaatha-server pull request #14
Opened 2023-07-06 09:55 UTC by Rup-Narayan-Rajbanshi

- Addresses #13 

## Changes
- Remove existing project app
- Add type into work.
- Add filter work type into works.

Mention related users here if any.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2023-07-06 11:07 UTC, subinasr requested changes

2023-07-06 11:07 UTC, subinasr commented on apps/work/models.py
> +        VISUALIZATION = 'visualization', 'Visualization'
Let's replace `Visualizations` with `Graphics and Visualizations`.

2023-07-06 11:10 UTC, thenav56 requested changes

2023-07-06 11:10 UTC, thenav56 commented on apps/work/types.py
> +    work_type: auto
```suggestion
    work_type: WorkTypeEnum
```

2023-07-06 11:28 UTC, thenav56 approved these changes

2023-07-06 11:38 UTC, subinasr commented
Let's add a 'workType' filter as well @Rup-Narayan-Rajbanshi

2023-07-07 04:23 UTC, thenav56 approved these changes

2023-07-07 05:01 UTC, subinasr approved these changes

2023-07-07 05:02 UTC, merged