Add test runner in github actions
storiesofgaatha/gaatha-server pull request #4
Opened 2023-02-08 06:01 UTC by Rup-Narayan-Rajbanshi

## Changes
- Add a test runner in github actions

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] tests
- [x] permission checks (tests here too)
- [ ] translations

2023-02-09 04:15 UTC, thenav56 requested changes
Looks good.

2023-02-09 04:15 UTC, thenav56 commented on .github/workflows/ci.yml
> +          docker-compose -f gh-docker-compose.yml run --rm server pytest -ra --reuse-db -v --durations=10
Let's create a script file and use that instead.
Something like this https://github.com/the-deep/server/blob/develop/scripts/run_tests.sh

2023-02-13 05:37 UTC, thenav56 approved these changes

2023-02-14 04:56 UTC, bimal125 approved these changes

2023-02-14 05:09 UTC, merged