Add project model
storiesofgaatha/gaatha-server pull request #5
Opened 2023-02-14 05:54 UTC by Rup-Narayan-Rajbanshi

## Address https://github.com/toggle-corp/gaatha-v2/issues/22
## Changes
- Add project model and respective graphql end point.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] tests
- [x] permission checks (tests here too)
- [x] translations

2023-02-15 03:47 UTC, bimal125 requested changes

2023-02-15 03:47 UTC, bimal125 commented on apps/project/models.py
> +    title = models.CharField(max_length=100, verbose_name=_('Title'))
Max length 100 will be sufficient?

2023-02-15 03:47 UTC, bimal125 commented on apps/project/models.py
> +    location = models.CharField(max_length=500, verbose_name=_('Location'))
We can further divide the location field into districts, provinces ...?

2023-02-15 03:47 UTC, bimal125 commented on apps/project/admin.py
> +    ]
We can add `search_fields`, `list_filter` too ? It might be easier for admin users.

2023-02-15 05:03 UTC, thenav56 requested changes

2023-02-15 05:03 UTC, thenav56 commented on README.md
> +
We might need another step for the .env setup as well.
```suggestion
- Create a **.env** file with the necessary environment variables. Check `?err` attributes in **docker-compose.yml** and **gaatha/settings.py**
```

2023-02-15 05:03 UTC, thenav56 commented on apps/project/apps.py
> +    default_auto_field = 'django.db.models.BigAutoField'
We should define this in settings.py.

2023-02-15 05:03 UTC, thenav56 commented on apps/project/models.py
> +    title = models.CharField(max_length=100, verbose_name=_('Title'))
cc: @subinasr

2023-02-15 05:03 UTC, thenav56 commented on apps/project/models.py
> +    location = models.CharField(max_length=500, verbose_name=_('Location'))
cc: @subinasr

2023-02-15 05:03 UTC, thenav56 commented on apps/project/types.py
> +        return build_url(self.image, info.context['request'])
Let's remove **build_url** and use **FileFieldType** directly.

Diff: [server.txt](https://github.com/toggle-corp/gaatha-server/files/10739426/server.txt)

cc: @subinasr 
> NOTE: This will change types to
> - FieldField! (Required)
> - Attributes:
>   - name: Optional
>   - url: Optional
>   - exists: (Required)

2023-02-15 05:36 UTC, Rup-Narayan-Rajbanshi commented on apps/project/admin.py
> +    ]
@bimal125 \
This model will have not more than five objects so may be it is not necessary.
@subinasr Is search and filter required ?

2023-02-15 05:37 UTC, Rup-Narayan-Rajbanshi commented on apps/project/models.py
> +    location = models.CharField(max_length=500, verbose_name=_('Location'))
@subinasr

2023-02-15 05:37 UTC, Rup-Narayan-Rajbanshi commented on apps/project/models.py
> +    title = models.CharField(max_length=100, verbose_name=_('Title'))
@subinasr

2023-02-15 08:01 UTC, subinasr commented on apps/project/models.py
> +    title = models.CharField(max_length=100, verbose_name=_('Title'))
Yes, this should be fine.

2023-02-15 08:02 UTC, subinasr commented on apps/project/models.py
> +    location = models.CharField(max_length=500, verbose_name=_('Location'))
As for now, the requirement is only for a free text field. Maybe we can do this later if our clients need it, but for now, this is fine.

2023-02-15 08:03 UTC, subinasr commented on apps/project/admin.py
> +    ]
I agreee with @Rup-Narayan-Rajbanshi, this will only ever hold five items. No search or filtering required.

2023-02-16 09:15 UTC, thenav56 approved these changes

2023-03-21 10:10 UTC, bimal125 approved these changes

2023-03-21 10:27 UTC, merged