Feature/add order to work
storiesofgaatha/gaatha-server pull request #8
Opened 2023-03-14 10:33 UTC by Rup-Narayan-Rajbanshi

## Changes
- Add position in work model and add ordering in work query.

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] n+1 queries
- [x] flake8 issues
- [x] `print`
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2023-03-14 10:45 UTC, bimal125 requested changes

2023-03-14 10:45 UTC, bimal125 commented on apps/work/models.py
> +    position = models.PositiveIntegerField(blank=True, null=True)
@Rup-Narayan-Rajbanshi  Positions are usually fixed, Enum will be good choice in this case
cc @subinasr

2023-03-15 05:49 UTC, subinasr commented on apps/work/models.py
> +    position = models.PositiveIntegerField(blank=True, null=True)
The number of work items can be as many as user wants, how do we work around that for enum fields?

2023-03-15 05:53 UTC, Rup-Narayan-Rajbanshi commented on apps/work/models.py
> +    position = models.PositiveIntegerField(blank=True, null=True)
@bimal125 , i agree with @subinasr

2023-03-15 11:41 UTC, thenav56 commented on apps/work/models.py
> +    position = models.PositiveIntegerField(blank=True, null=True)
Maybe the terminology is confusing here? We are talking about the order.
Maybe use `order` or add a **help_text** defining this is used to sort works.

2023-03-15 14:30 UTC, bimal125 commented on apps/work/models.py
> +    position = models.PositiveIntegerField(blank=True, null=True)
@Rup-Narayan-Rajbanshi   I  am resolving this, lets's change position to order as @thenav56  mentioned above.

2023-03-17 10:45 UTC, thenav56 approved these changes

2023-03-21 10:09 UTC, bimal125 approved these changes

2023-03-21 10:13 UTC, merged